name: 'Your name here'
description: 'Provide a description here'
author: 'Your name or organization here'
branding:
  color: green
  icon: book-open
inputs:
  myToken:
    required: true
    description: 'your github token'
runs:
  using: 'node12'
  main: 'dist/index.js'
