name: "CodeTest"
on:
  workflow_dispatch:
  # schedule:
  #   - cron: "42 0 * * * *"
  pull_request:


jobs:


  # test action works running from the graph
  selftest:
    runs-on: ubuntu-latest #  [self-hosted]
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        with:
          myToken: ${{ secrets.GITHUB_TOKEN }}
